d3.csv("data.csv").then(function(t) { t.forEach(function(t) { t.key = t["Epic Link"], t.total = +t.Total }); var e = $("#chart").width() - 50 - 50,
        a = .6 * $(window).innerHeight() - 10 - 50,
        r = d3.select("#chart").append("svg").attr("width", e + 50 + 50).attr("height", a + 10 + 50).append("g").attr("transform", "translate(50,10)"),
        l = d3.select("#chart").append("div").attr("id", "tooltip").style("position", "absolute").style("visibility", "hidden"),
        n = d3.scaleLinear().domain([0, d3.max(t, t => t.total)]).range([0, e]);
    d3.scaleSequential().interpolator(function piecewise(t, e) { for (var a = 0, r = e.length - 1, i = e[0], l = new Array(r < 0 ? 0 : r); a < r;) l[a] = t(i, i = e[++a]); return function(t) { var e = Math.max(0, Math.min(r - 1, Math.floor(t *= r))); return l[e](t - e) } }(d3.interpolateRgb, ["white", "yellow"])).domain([0, t.length]), r.append("g").attr("transform", "translate(0," + a + ")").attr("class", "axis").call(d3.axisBottom(n)), r.append("text").attr("class", "axis").attr("transform", "translate(" + e / 2 + " ," + (a + 10 + 20) + ")").style("text-anchor", "middle").text("Size of Epic (Number of User Stories"); var o = d3.histogram().value(function(t) { return t.total }).domain(n.domain()).thresholds(n.ticks(n.domain()[1] / 5))(t);
    o.unshift({ x0: 0, x1: 0, length: 0 }); var s = d3.scaleLinear().range([a, 0]).domain([0, d3.max(o, function(t) { return t.length })]);
    r.append("g").attr("class", "axis").call(d3.axisLeft(s)), r.append("text").attr("class", "axis").attr("transform", "rotate(-90)").attr("y", -50).attr("x", 0 - a / 2).attr("dy", "1em").style("text-anchor", "middle").text("Frequency of Epic Size"), r.selectAll("rect").data(o).enter().append("rect").attr("class", "bar").attr("x", 1).attr("transform", function(t) { return "translate(" + n(t.x0) + "," + s(t.length) + ")" }).attr("width", function(t) { return n(t.x1) - n(t.x0) - 1 }).attr("height", function(t) { return a - s(t.length) }).style("fill", "white").style("opacity", .3); var c = d3.area().x(t => n(t.x0) + (n(t.x1) - n(t.x0)) / 2).y0(s(0)).y1(t => s(t.length)),
        d = r.append("path").data([o]).attr("class", "path").attr("id", "areachart").attr("clip-path", "url(#clip)").attr("d", c).style("stroke-width", "2px").style("stroke", "#FDBB32").style("fill", "#FDBB32").style("fill-opacity", .2),
        h = r.append("g").attr("class", "mouse-over-effects");
    h.append("line").attr("class", "mouse-line").style("stroke-width", "1px").style("opacity", "0"), h.append("circle").attr("id", "circle").attr("class", "hoverCircle").attr("r", 7).style("stroke-width", "1px").style("opacity", "0"), h.append("rect").attr("width", e).attr("height", a).attr("fill", "none").attr("pointer-events", "all").on("mouseout", function() { d3.selectAll(".hoverCircle").transition().style("opacity", "0"), d3.selectAll(".hoverBackground").transition().style("opacity", "0"), d3.selectAll(".hoverText").transition().style("opacity", "0"), d3.select("#areachart").transition().style("opacity", "0"), l.transition().style("visibility", "hidden"), d3.selectAll(".bar").transition().style("opacity", .3) }).on("mouseover", function() { d3.selectAll(".hoverCircle").transition().style("opacity", "1"), d3.selectAll(".hoverBackground").transition().style("opacity", "1"), d3.selectAll(".hoverText").transition().style("opacity", "1"), d3.select("#areachart").transition().style("opacity", "1"), d3.selectAll(".bar").transition().style("opacity", .1) }).on("mousemove", function() {! function updateMouseOver(e, r) { var o = document.getElementById("chart").offsetLeft,
                s = d.node(),
                c = s.getTotalLength(),
                h = d3.bisector(t => t.x1).right;
            d3.selectAll(".mouse-line").attr("x1", e[0]).attr("x2", e[0]).attr("y1", a).attr("y2", 0), d3.select("#clip").select("rect").attr("width", e[0]); var f = d3.event.pageX - o - 50 - 14,
                u = r[h(r, n.invert(f))],
                g = h(r, n.invert(f)),
                x = d3.sum(r.slice(0, g + 1), t => t.length); for (i = f; i < c; i += 1) { var m = s.getPointAtLength(i); if (m.x >= f) break }
            d3.select("#circle").style("fill", "white").style("opacity", 1).attr("cx", f).attr("cy", m.y); var v = d3.mouse(p.node());
            y.x = window.scrollX, y.y = window.scrollY, l.style("right", ""), l.style("left", ""), l.style("bottom", ""), l.style("top", ""), l.html("<p id='heading'><span style='color:#FDBB32;'> " + x + " Epics </span>(or " + d3.format(".0%")(x / t.length) + " of the " + t.length + " Epics recorded) <span style='color:#FDBB32;'><br>hold " + u.x1 + " User Stories </span>or less within them.</p>"), l.style("height", $("#heading").height()), v[0], y.x, y.w, l.style("left", f + 50 + 15 + "px"), v[1], y.y, y.h, l.style("top", m.y - $("#tooltip").height() - 15 + "px"), l.style("visibility", "visible") }(d3.mouse(this), o) }), r.append("clipPath").attr("id", "clip").append("rect").attr("x", 0).attr("y", 0).attr("width", e).attr("height", a); var p = d3.select("svg"),
        y = { x: window.scrollX, y: window.scrollY, w: window.innerWidth, h: window.innerHeight },
        f = d3.select("#chart");
    f.node().offsetWidth, f.node().offsetHeight, document.width, document.height,
        function getNodePos(t) { for (var e = d3.select("body").node(); null != t && t != e; t.offsetLeft || t.clientLeft, t.offsetTop || t.clientTop, t = t.offsetParent || t.parentNode); }(p.node()) });